version: '3'

services:
  elastalert:
    image: 'praecoapp/elastalert-server'

    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'praecoapp/praeco'
#    environment:
#      VUE_APP_BASE_URL: /my-path/

