version: '3'

services:
  elastalert:
    image: 'elastalert-server'
    build: 
      context: elastalert/
    networks:
      main-overlay:
        ipv4_address: 10.0.2.93  

    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'praeco'
    build: 
      context: praecoapp/
    networks:
      main-overlay:
        ipv4_address: 10.0.2.94 
#    environment:
#      VUE_APP_BASE_URL: /my-path/

networks:
  main-overlay:
    external: true
