version: '3'

services:
  elastalert:
    image: 'praecoapp/elastalert-server'
    networks:
      main-overlay:
        ipv4_address: 10.0.2.93  

    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'

  webapp:
    image: 'praecoapp/praeco'
#    environment:
#      VUE_APP_BASE_URL: /my-path/

  networks:
    main-overlay:
      external: true
