FROM elastalert-server

ADD config/elastalert.yaml /opt/elastalert/config.yaml
ADD config/api.config.json /opt/elastalert-server/config/config.json
ADD rules /opt/elastalert/rules
#ADD /rule_templates /opt/elastalert/rule_templates
